language: node_js

node_js:
  - "stable"

script:
  - npm test
  - npm run coverage

before_script:
  - npm install codeclimate-test-reporter instanbul nyc -g

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info

addons:
  code_climate:
    repo_token: 