
const mockData = {
  user1: {
    firstName: 'John',
    lastName: 'Wick',
    username: 'black',
    email: 'johnwick@gmail.com',
  },
  user2: {
    firstName: 'Strawhat',
    lastName: 'Luffy',
    username: 'strawhat',
    email: 'strawhat@gmail.com',
  },
  user3: {
    firstName: 'Naruto',
    lastName: 'Uzumaki',
    username: 'naruto',
    email: 'naruto@gmail.com',
  },
  user4: {
    username: 'fattylee',
    email: 'fattty@gmail.com',
  },
  user5: {
    username: 'unknown',
    email: 'unknown@gmail.com',
  },
  user6: {
    firstName: 'Big',
    lastName: 'Badwolf',
    username: 'badwolf',
    email: 'bigbadwolf@gmail.com',
    password: 'Bigbadw0lf!',
  },
  user7: {
    id: 3,
    firstName: 'Strawhat',
    lastName: 'Luffy',
    username: 'strawhat',
    email: 'strawhat@gmail.com',
    password: 'Bigbadw0lf!',
  },

  user8: {
    firstName: 'NewFirstName',
    lastName: 'NewLastName',
    username: 'usernameIsHere',
    email: 'newemail@gmail.com',
    password: 'Bigbadw0lf!',
    bio: 'newBio',
    image: 'http://thisisaurl/image.png',
  },
  existingUser: {
    firstName: 'thisUserFirstName',
    lastName: 'thisUserLastName',
    username: 'thisuserexists',
    email: 'thisuserexists@gmail.com',
    hash: 'BigbGadw0lf!',
    password: 'BigbGadw0lf!',
    bio: 'whatabio',
  },
  likeUser: {
    firstName: 'Chidiebere',
    lastName: 'TheGreat',
    username: 'username101',
    hash: 'R!vend1elLl121//',
    verified: true,
    email: 'username1e12@gmail.com',
  },
  unverifiedUser: {
    firstName: 'Stevo',
    lastName: 'mainMan',
    username: 'stevemain10101',
    hash: 'R!vend1elLl121//',
    verified: false,
    email: 'userwithName@gmail.com',
  },
  author3: {
    firstName: 'Strawhat',
    lastName: 'Luffy',
    username: 'strawhat',
    email: 'strawhat@gmail.com',
  },
  follow5: {
    firstName: 'Fatty',
    lastName: 'Lee',
    username: 'fattylee',
    email: 'fattty@gmail.com',
  },
  unverified: {
    firstName: 'Gadath',
    lastName: 'Pillow',
    username: 'pillowgad',
    email: 'pillowgad@gmail.com',
  },
  follow7: {
    firstName: 'Krista',
    lastName: 'Kolo',
    username: 'kolokris',
    email: 'kolokris@gmail.com',
  },
  follow8: {
    firstName: 'Zebedee',
    lastName: 'Macus',
    username: 'zebedee',
    email: 'zebedee@gmail.com',
  },
  followerProfile: {
    firstName: 'Fatty',
    lastName: 'Lee',
    username: 'fattylee',
    bio: null,
    image: null,
  },
  followingProfile: {
    firstName: 'Zebedee',
    lastName: 'Macus',
    username: 'zebedee',
    bio: null,
    image: null,
  },
  megameUser1: {
    firstName: 'Charlie',
    lastName: 'Brown',
    username: 'charlieBrown',
    email: 'charlieBrown@gmail.com',
  },
  megameUser2: {
    firstName: 'Mary',
    lastName: 'Jane',
    username: 'maryJane',
    email: 'maryJane@gmail.com',
  },
  megameUser3: {
    firstName: 'Charlie1',
    lastName: 'Brown1',
    username: 'charlieBrown1',
    email: 'charlieBrown1@gmail.com',
  },
  megameArticle1: {
    title: 'article 1',
    description: 'article 1',
    body: 'article 1',
    slug: 'article-1-1',
    image: null,
    authorId: 1,
  },
  authorTag: {
    firstName: 'Tager',
    lastName: 'Author',
    username: 'authorTager',
    hash: 'R!vend1elLl121//',
    verified: true,
    email: 'authortager@gmail.com',
  },
  article1: {
    title: 'My greatest love',
    description: 'love',
    body: 'I love my mother very muc',

  },
  tags1: ['life', 'death', 'music'],
  tags2: [
    'sorrow', 'blood', 'education', 'life', 'death', 'no', 'way',
    'sorrw', 'blod', 'educatin', 'lif', 'deah', 'n', 'wa',
    'lfe', 'eath', 'msic', 'ife', 'deth', 'musc',
    'sorrow1', 'blood2', 'education3', 'life4', 'death5', 'no6', 'way7',
    'sorrw3', 'blod3', 'educa3tin', 'li3f', '89', 'n1', 'wa1',
    'lf3e', '3eath', 'msic3', '1fe', '6eth', '9usc',
  ],
  notificationUser1: {
    firstName: 'notification1',
    lastName: 'notification1',
    username: 'notification1',
    email: 'notification1@gmail.com',
  },
  notificationUser2: {
    firstName: 'notification',
    lastName: 'notification',
    username: 'notification',
    email: 'notification@gmail.com',
  },
  notificationUser3: {
    firstName: 'notification2',
    lastName: 'notification2',
    username: 'notification2',
    email: 'notification2@gmail.com',
  },
  notificationUser4: {
    firstName: 'notification4',
    lastName: 'notification4',
    username: 'notification4',
    email: 'notification4@gmail.com',
  },
  notificationUser5: {
    firstName: 'notification5',
    lastName: 'notification5',
    username: 'notification5',
    email: 'notification5@gmail.com',
  },
  notificationUser6: {
    firstName: 'notification6',
    lastName: 'notification6',
    username: 'notification6',
    email: 'notification6@gmail.com',
  },
  notifUser1Article: {
    title: 'article notification',
    description: 'article notification',
    body: 'article notification',
    slug: 'article-notification',
    authorId: 'fbf941c0-aa8c-11e8-a375-d331f0a71356',
  },
};

export default mockData;
